language:
  - cpp

compiler:
  - gcc
  
before_install:
  - sudo add-apt-repository ppa:timsc/opencv-3.4 -y
  - sudo apt-get update

install:

  - sudo apt-get install -y build-essential
  - sudo apt-get install -y cmake git libopencv-dev

script: build.sh